- hosts: all
  gather_facts: False
  tasks:
    
    - name: Create the .ssh directory in the container
      file:
        path: "~/.ssh"
        state: directory
        mode: '0755'
      delegate_to: 127.0.0.1
      run_once: True
    
    - name: generate SSH key
      openssh_keypair:
        path: "~/.ssh/id_rsa_its"
        type: rsa
        size: 4096
        state: present
        force: no
      delegate_to: 127.0.0.1
      run_once: True
    
    - name: Deploy public key
      authorized_key:
        user: devops
        key: "{{ lookup('file', '~/.ssh/id_rsa_its.pub') }}"
        state: present
      delegate_to: my-docker-host
      run_once: True

