---
- hosts: all
  gather_facts: False
  tasks:
    - name: Catch the linux distribution of the host
      shell: cat /etc/*release*
      register: MY_DISTRIB

    - name: Display the linux distribution
      debug:
        msg: "{{ MY_DISTRIB.stdout }}"

    - name: Check the debug message
      debug:
        msg: "Hi! Ansible is working"
